### ISSUE TITLE
How can we contribute

### ISSUE THREAD

**Issue by luisllamasbinaburo** [lrusso/ArduinoSimulator#3]
Hello @lrusso. I like your library, and i want to contribute and use it on my website (offcourse, giving attribution and including a link to this github)

I will like to try to add the feature of change a digital or analog input, when they are declare as input
Also, i will like to think about how to introduce interruptions on the simulation

But, before making a big PR or a new branch, i will like to ask you how do you prefer we to contribute, and which features are most useful to you.

Thanks for your work!

**Comment by lrusso** [comment]
Hello Luis, thank you for your message and interest in this project, I just approved and merged your PR with the simplified logic for the CPP code. You are free to use this simulator on your website if you include a link to this repo and attribution as required. Regarding the next step that I'm currently working on is to finish the EEPROM library/implementation. Any contribution related to that will be appreciated. Best regards, Leonardo.
